version: '3.9'

services:
  client:
    container_name: client_next
    image: client_next
    restart: always
    environment:
      - REACT_APP_NODE_ENV=production
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    container_name: server
    image: server
    restart: always
    environment:
      - DOCKER_CONTAINER=true
      - NODE_ENV=production
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo_db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
