version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: 'mongo_db'
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
