version: '3.9'

services:
  backend:
    container_name: backend
    image: backend
    restart: always
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
