version: '3.9'

services:
  server:
    container_name: server
    image: server
    restart: always
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db

volumes:
  mongodb:
